#! /bin/bash

ln -s .. tmp

#echo "merging book..."
ipython merge_book.py

echo "creating pdf..."
ipython nbconvert --to latex --template book book.ipynb
ipython to_pdf.py

mv book.pdf Kalman_and_Bayesian_Filters_in_Python.pdf

unlink tmp
